volumes:
  postgresql:
    driver: local

networks:
  app-network:
    driver: bridge

services:
  db:
    image: "postgres:15.1-alpine"
    container_name: postgres
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - app-network
  application:
    build: .
    container_name: survey_snp_bot
    depends_on:
      - db
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_PASSWORD: ${DB_PASSWORD}
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_NAME: ${BOT_NAME}
    networks:
      - app-network